param(
    [Parameter(Mandatory=$true)]
    [string]$BookName,

    [switch]$AutoNumber
)

[Console]::InputEncoding  = [System.Text.Encoding]::UTF8
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
$OutputEncoding = [System.Text.Encoding]::UTF8
chcp 65001 | Out-Null

$CommonPath = Join-Path (Split-Path -Parent $MyInvocation.MyCommand.Path) "00-common.ps1"
. $CommonPath

$Context = Get-SageContext -ScriptPath $MyInvocation.MyCommand.Path -BookName $BookName
Initialize-SageObservability -Context $Context
Set-SageCurrentStep -Context $Context -Step "build" -Data @{
    auto_number = [bool]$AutoNumber
}

$WorkspaceRoot = $Context.WorkspaceRoot
$BookRoot = $Context.BookRoot
$ChapterRoot = Join-Path $BookRoot "02_chapters"
$OutputRoot = Join-Path $BookRoot "04_output"
$LogRoot = $Context.LogRoot

if (!(Test-Path $WorkspaceRoot)) {
    Fail-SageStep -Context $Context -Step "build" -Message "Workspace not found." -Data @{ workspace = $WorkspaceRoot }
    Write-Error "Workspace not found: $WorkspaceRoot"
    exit 1
}

if (!(Test-Path $ChapterRoot)) {
    Fail-SageStep -Context $Context -Step "build" -Message "Chapter folder not found." -Data @{ chapter_root = $ChapterRoot }
    Write-Error "Chapter folder not found: $ChapterRoot"
    exit 1
}

if (!(Test-Path $OutputRoot)) {
    New-Item -ItemType Directory -Path $OutputRoot -Force | Out-Null
}

if (!(Test-Path $LogRoot)) {
    New-Item -ItemType Directory -Path $LogRoot -Force | Out-Null
}

if (!(Get-Command pandoc -ErrorAction SilentlyContinue)) {
    Fail-SageStep -Context $Context -Step "build" -Message "Pandoc not found." -Data @{}
    Write-Error "Pandoc not found."
    exit 1
}

$mdFiles = Get-ChildItem $ChapterRoot -Filter *.md |
    Where-Object { $_.Name -notmatch "^_" } |
    Sort-Object {
        if ($_.BaseName -match "^\d+") {
            [int]$matches[0]
        }
        else {
            9999
        }
    }

if ($mdFiles.Count -eq 0) {
    Fail-SageStep -Context $Context -Step "build" -Message "No markdown files found." -Data @{ chapter_root = $ChapterRoot }
    Write-Error "No markdown files found."
    exit 1
}

Write-Host "Found $($mdFiles.Count) chapter files."
Write-Host ""

foreach ($file in $mdFiles) {
    Write-Host "Adding: $($file.Name)"
}

$MetaFile = Join-Path $ChapterRoot "_metadata.yaml"

@"
title: "$BookName"
author: "Generated by SageWrite"
date: "$(Get-Date -Format yyyy-MM-dd)"
"@ | Set-Content $MetaFile -Encoding utf8

$OutputFile = Join-Path $OutputRoot "$BookName`_full.docx"
$PandocArgs = @()
$PandocArgs += $mdFiles.FullName
$PandocArgs += "--metadata-file=$MetaFile"
$PandocArgs += "-o"
$PandocArgs += $OutputFile
$PandocArgs += "--toc"
$PandocArgs += "--standalone"

if ($AutoNumber) {
    Write-Host ""
    Write-Host "Auto numbering enabled."
    $PandocArgs += "--number-sections"
}
else {
    Write-Host ""
    Write-Host "Auto numbering disabled."
}

try {
    & pandoc @PandocArgs

    if (!(Test-Path $OutputFile)) {
        throw "Pandoc build failed."
    }

    Write-Host ""
    Write-Host "Build completed successfully:"
    Write-Host $OutputFile
}
catch {
    Fail-SageStep -Context $Context -Step "build" -Message "Build failed." -Data @{
        output = $OutputFile
        error = $_.Exception.Message
    }
    Write-Error "Build failed: $_"
    exit 1
}
finally {
    Remove-Item $MetaFile -ErrorAction SilentlyContinue
}

Complete-SageStep -Context $Context -Step "build" -State "success" -Message "Document build completed." -Data @{
    output = $OutputFile
    chapter_count = $mdFiles.Count
    auto_number = [bool]$AutoNumber
}
