param(
    [Parameter(Mandatory = $true)]
    [string]$BookName,

    [string]$Language = "zh",

    [switch]$AutoNumber
)

[Console]::InputEncoding  = [System.Text.Encoding]::UTF8
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
$OutputEncoding = [System.Text.Encoding]::UTF8
chcp 65001 | Out-Null

$CommonPath = Join-Path (Split-Path -Parent $MyInvocation.MyCommand.Path) "00-common.ps1"
. $CommonPath

$Context = Get-SageContext -ScriptPath $MyInvocation.MyCommand.Path -BookName $BookName
Initialize-SageObservability -Context $Context
$LanguageCode = $Language.Trim().ToLowerInvariant()
if ([string]::IsNullOrWhiteSpace($LanguageCode)) {
    $LanguageCode = "zh"
}
Set-SageCurrentStep -Context $Context -Step "build_epub" -Data @{
    language = $LanguageCode
    auto_number = [bool]$AutoNumber
}

$WorkspaceRoot = $Context.WorkspaceRoot
$BookRoot = $Context.BookRoot
$SourceRoot = if ($LanguageCode -eq "zh") {
    $BookRoot
} else {
    Join-Path $BookRoot ("03_translation\" + $LanguageCode)
}
$ObjectivePath = Join-Path $SourceRoot "00_brief\objective.md"
$ChapterRoot = Join-Path $SourceRoot "02_chapters"
$OutputRoot = Join-Path $BookRoot ("04_output\" + $LanguageCode)
$LogRoot = $Context.LogRoot
$BuildTempRoot = Join-Path $LogRoot ("_build_epub_tmp_" + $LanguageCode)

function Get-FrontMatterValue {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Content,

        [Parameter(Mandatory = $true)]
        [string]$Key
    )

    $Normalized = $Content -replace "`r", ""
    if (-not $Normalized.StartsWith("---`n")) {
        return $null
    }

    $Match = [regex]::Match($Normalized, "(?s)^---\n(.*?)\n---\n?")
    if (-not $Match.Success) {
        return $null
    }

    $Pattern = "(?m)^" + [regex]::Escape($Key) + ":\s*(.+?)\s*$"
    $ValueMatch = [regex]::Match($Match.Groups[1].Value, $Pattern)
    if (-not $ValueMatch.Success) {
        return $null
    }

    return $ValueMatch.Groups[1].Value.Trim().Trim('"')
}

function Get-MarkdownBodyText {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Content
    )

    $Normalized = $Content -replace "`r", ""
    if ($Normalized.StartsWith("---`n")) {
        $Match = [regex]::Match($Normalized, "(?s)^---\n.*?\n---\n?")
        if ($Match.Success) {
            return $Normalized.Substring($Match.Length).Trim()
        }
    }

    return $Normalized.Trim()
}

if (!(Test-Path $WorkspaceRoot)) {
    Fail-SageStep -Context $Context -Step "build_epub" -Message "Workspace not found." -Data @{ workspace = $WorkspaceRoot; language = $LanguageCode }
    Write-Error "Workspace not found: $WorkspaceRoot"
    exit 1
}

if (!(Test-Path $SourceRoot)) {
    Fail-SageStep -Context $Context -Step "build_epub" -Message "Language source root not found." -Data @{ source_root = $SourceRoot; language = $LanguageCode }
    Write-Error "Language source root not found: $SourceRoot"
    exit 1
}

if (!(Test-Path $ChapterRoot)) {
    Fail-SageStep -Context $Context -Step "build_epub" -Message "Chapter folder not found." -Data @{ chapter_root = $ChapterRoot; language = $LanguageCode }
    Write-Error "Chapter folder not found: $ChapterRoot"
    exit 1
}

if (!(Test-Path $OutputRoot)) {
    New-Item -ItemType Directory -Path $OutputRoot -Force | Out-Null
}

if (!(Test-Path $LogRoot)) {
    New-Item -ItemType Directory -Path $LogRoot -Force | Out-Null
}

if (!(Get-Command pandoc -ErrorAction SilentlyContinue)) {
    Fail-SageStep -Context $Context -Step "build_epub" -Message "Pandoc not found." -Data @{ language = $LanguageCode }
    Write-Error "Pandoc not found."
    exit 1
}

$mdFiles = Get-ChildItem $ChapterRoot -Filter *.md |
    Where-Object { $_.Name -notmatch "^_" } |
    Sort-Object {
        if ($_.BaseName -match "^\d+") {
            [int]$matches[0]
        }
        else {
            9999
        }
    }

if ($mdFiles.Count -eq 0) {
    Fail-SageStep -Context $Context -Step "build_epub" -Message "No markdown files found." -Data @{ chapter_root = $ChapterRoot; language = $LanguageCode }
    Write-Error "No markdown files found."
    exit 1
}

Write-Host "Found $($mdFiles.Count) chapter files."
Write-Host ""

foreach ($file in $mdFiles) {
    Write-Host "Adding: $($file.Name)"
}

$DocumentTitle = $BookName
$DocumentAuthor = "Generated by SageWrite"
if (Test-Path $ObjectivePath) {
    $ObjectiveRaw = Get-Content -LiteralPath $ObjectivePath -Raw -Encoding UTF8
    $ObjectiveTitle = Get-FrontMatterValue -Content $ObjectiveRaw -Key "title"
    $ObjectiveAuthor = Get-FrontMatterValue -Content $ObjectiveRaw -Key "author"
    if (-not [string]::IsNullOrWhiteSpace($ObjectiveTitle)) {
        $DocumentTitle = $ObjectiveTitle
    }
    if (-not [string]::IsNullOrWhiteSpace($ObjectiveAuthor)) {
        $DocumentAuthor = $ObjectiveAuthor
    }
}

$TitleYamlLines = @("title: |")
$TitleYamlLines += ($DocumentTitle -split "`r?`n" | ForEach-Object { "  $_" })
$MetaContent = @(
    $TitleYamlLines
    "author: ""$DocumentAuthor"""
    "date: ""$(Get-Date -Format yyyy-MM-dd)"""
) -join "`r`n"

if (Test-Path $BuildTempRoot) {
    Remove-Item $BuildTempRoot -Recurse -Force -ErrorAction SilentlyContinue
}
New-Item -ItemType Directory -Path $BuildTempRoot -Force | Out-Null

$BuildFiles = @()
foreach ($file in $mdFiles) {
    $Raw = Get-Content -LiteralPath $file.FullName -Raw -Encoding UTF8
    $Body = Get-MarkdownBodyText -Content $Raw
    $TempPath = Join-Path $BuildTempRoot $file.Name
    Set-Content -LiteralPath $TempPath -Encoding utf8 -Value $Body
    $BuildFiles += $TempPath
}

$MetaFile = Join-Path $BuildTempRoot "_metadata_epub.yaml"
$MetaContent | Set-Content -LiteralPath $MetaFile -Encoding utf8

$OutputFile = Join-Path $OutputRoot "$BookName`_full.epub"
$BackupRoot = Join-Path $OutputRoot "back"
$BackupFile = $null

if (Test-Path $OutputFile) {
    New-Item -ItemType Directory -Path $BackupRoot -Force | Out-Null
    $Stamp = Get-Date -Format "yyyyMMdd_HHmmss"
    $BackupFile = Join-Path $BackupRoot ("{0}_{1}{2}" -f $BookName, $Stamp, [System.IO.Path]::GetExtension($OutputFile))
    Copy-Item -LiteralPath $OutputFile -Destination $BackupFile -Force
    Write-Host ""
    Write-Host "Backed up existing output to:"
    Write-Host $BackupFile

    try {
        Remove-Item -LiteralPath $OutputFile -Force -ErrorAction Stop
    }
    catch {
        Fail-SageStep -Context $Context -Step "build_epub" -Message "Existing EPUB file is locked." -Data @{
            output = $OutputFile
            backup_output = $BackupFile
            error = $_.Exception.Message
            language = $LanguageCode
        }
        Write-Error "Existing EPUB file is locked. Please close any reader or sync process and try again: $OutputFile"
        exit 1
    }
}

$PandocArgs = @()
$PandocArgs += $BuildFiles
$PandocArgs += "--metadata-file=$MetaFile"
$PandocArgs += "-o"
$PandocArgs += $OutputFile
$PandocArgs += "--toc"
$PandocArgs += "--standalone"

if ($AutoNumber) {
    Write-Host ""
    Write-Host "Auto numbering enabled."
    $PandocArgs += "--number-sections"
}
else {
    Write-Host ""
    Write-Host "Auto numbering disabled."
}

try {
    & pandoc @PandocArgs
    $PandocExitCode = $LASTEXITCODE

    if ($PandocExitCode -ne 0) {
        throw "Pandoc exited with code $PandocExitCode."
    }

    if (!(Test-Path $OutputFile)) {
        throw "Pandoc EPUB build failed."
    }

    Write-Host ""
    Write-Host "EPUB build completed successfully:"
    Write-Host $OutputFile
}
catch {
    Fail-SageStep -Context $Context -Step "build_epub" -Message "EPUB build failed." -Data @{
        output = $OutputFile
        error = $_.Exception.Message
        language = $LanguageCode
    }
    Write-Error "EPUB build failed: $_"
    exit 1
}
finally {
    Remove-Item -LiteralPath $MetaFile -ErrorAction SilentlyContinue
    Remove-Item $BuildTempRoot -Recurse -Force -ErrorAction SilentlyContinue
}

Complete-SageStep -Context $Context -Step "build_epub" -State "success" -Message "EPUB build completed." -Data @{
    language = $LanguageCode
    source_root = $SourceRoot
    output = $OutputFile
    backup_output = $BackupFile
    chapter_count = $mdFiles.Count
    document_title = $DocumentTitle
    document_author = $DocumentAuthor
    auto_number = [bool]$AutoNumber
}
