param(
    [Parameter(Mandatory=$true)]
    [string]$BookName,

    [switch]$AutoNumber
)

# ===============================
# Force UTF-8 Console
# ===============================

[Console]::InputEncoding  = [System.Text.Encoding]::UTF8
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
$OutputEncoding = [System.Text.Encoding]::UTF8
chcp 65001 | Out-Null

# ===============================
# Resolve Root Paths
# ===============================

$EnginePath = Split-Path -Parent $MyInvocation.MyCommand.Path
$SageRoot   = Split-Path -Parent $EnginePath
$ClawRoot   = Split-Path -Parent $SageRoot

$WorkspaceRoot = Join-Path $ClawRoot "workspace-$BookName"
$BookRoot      = Join-Path $WorkspaceRoot "sagewrite\book"
$ChapterRoot   = Join-Path $BookRoot "02_chapters"
$OutputRoot    = Join-Path $BookRoot "04_output"
$LogRoot       = Join-Path $BookRoot "logs"

# ===============================
# Validate
# ===============================

if (!(Test-Path $WorkspaceRoot)) {
    Write-Error "Workspace not found: $WorkspaceRoot"
    exit 1
}

if (!(Test-Path $ChapterRoot)) {
    Write-Error "Chapter folder not found: $ChapterRoot"
    exit 1
}

if (!(Test-Path $OutputRoot)) {
    New-Item -ItemType Directory -Path $OutputRoot | Out-Null
}

if (!(Test-Path $LogRoot)) {
    New-Item -ItemType Directory -Path $LogRoot | Out-Null
}

# ===============================
# Check Pandoc
# ===============================

if (!(Get-Command pandoc -ErrorAction SilentlyContinue)) {
    Write-Error "Pandoc not found."
    exit 1
}

# ===============================
# Collect Markdown Files
# ===============================

$mdFiles = Get-ChildItem $ChapterRoot -Filter *.md |
    Where-Object { $_.Name -notmatch "^_" } |
    Sort-Object {
        if ($_.BaseName -match "^\d+") {
            [int]$matches[0]
        } else {
            9999
        }
    }

if ($mdFiles.Count -eq 0) {
    Write-Error "No markdown files found."
    exit 1
}

Write-Host "Found $($mdFiles.Count) chapter files."
Write-Host ""

foreach ($file in $mdFiles) {
    Write-Host "Adding: $($file.Name)"
}

# ===============================
# Metadata
# ===============================

$MetaFile = Join-Path $ChapterRoot "_metadata.yaml"

@"
title: "$BookName"
author: "Generated by SageWrite"
date: "$(Get-Date -Format yyyy-MM-dd)"
"@ | Set-Content $MetaFile -Encoding UTF8

# ===============================
# Build Arguments
# ===============================

$OutputFile = Join-Path $OutputRoot "$BookName`_full.docx"

$PandocArgs = @()

$PandocArgs += $mdFiles.FullName
$PandocArgs += "--metadata-file=$MetaFile"
$PandocArgs += "-o"
$PandocArgs += $OutputFile
$PandocArgs += "--toc"
$PandocArgs += "--standalone"

if ($AutoNumber) {
    Write-Host ""
    Write-Host "Auto numbering enabled."
    $PandocArgs += "--number-sections"
} else {
    Write-Host ""
    Write-Host "Auto numbering disabled."
}

# ===============================
# Execute Build
# ===============================

try {

    & pandoc @PandocArgs

    if (!(Test-Path $OutputFile)) {
        throw "Pandoc build failed."
    }

    Write-Host ""
    Write-Host "Build completed successfully:"
    Write-Host $OutputFile
}
catch {
    Write-Error "Build failed: $_"
    exit 1
}
finally {
    Remove-Item $MetaFile -ErrorAction SilentlyContinue
}